### ISSUE TITLE
Add/Edit layout to support "Improve this page"

### ISSUE THREAD

**Issue by mdrmike** [uncodedlb/hacknights#4]
Per discussion with @poproar to create `Improve this page` :pencil2:  functionality similar to https://jekyllrb.com/docs/home/, Add (or edit) a `_layout` 

[Example from Jekyll Docs](https://github.com/jekyll/jekyll/blob/master/docs/_layouts/docs.html)

```
<div class="improve right hide-on-mobiles">
            <a href="https://github.com/jekyll/jekyll/edit/master/docs/{{ page.path }}"><i class="fa fa-pencil"></i> &nbsp;Improve this page</a>
</div>
```

**Comment by poproar** [comment]
Thanks

**Comment by poproar** [comment]
It is all set to go but now it seems that pull requests are a mess

**Comment by mdrmike** [comment]
@poproar  @arthursucks  Pull requests a mess? I'm not sure what that means. Hit me up on uncodedlb.slack.com

**Comment by poproar** [comment]
7b3caeed51347db60b436ef762e88405970553a8
