### ISSUE TITLE
Merge duplicate work (but different filenames)

### ISSUE THREAD

**Issue by mdrmike** [uncodedlb/hacknights#5]
Merge work that @poproar also did (but didn't close issue, so I did it too)  :smiley_cat: 

README.md :twisted_rightwards_arrows: README.markdown
contributing.md :twisted_rightwards_arrows: /about/contribute.markdown

**Comment by poproar** [comment]
Should I just delete them?

**Comment by mdrmike** [comment]
@poproar Your call.  The content is different.  I like aspects of what we both did ... but deleting is fast and easy, too.  :wink:

**Comment by poproar** [comment]
deleted
